INSERT INTO carros.carros_marca (marca) VALUES ('Audi');
INSERT INTO carros.carros_marca (marca) VALUES ('BMW');
INSERT INTO carros.carros_marca (marca) VALUES ('Citroen');
INSERT INTO carros.carros_marca (marca) VALUES ('Chevrolet');
INSERT INTO carros.carros_marca (marca) VALUES ('Fiat');
INSERT INTO carros.carros_marca (marca) VALUES ('Ford');
INSERT INTO carros.carros_marca (marca) VALUES ('Honda');
INSERT INTO carros.carros_marca (marca) VALUES ('Hyundai');

INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (1,'A3');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (2,'X1');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (3,'C4');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (5,'500');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (5,'Palio');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (4,'Agile');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (4,'Captiva');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (7,'Civic');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (7,'Fit');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (8,'Veloster');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (8,'Elantra');
INSERT INTO carros.carros_modelo (marca_id, modelo) VALUES (8,'i30');

INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (1,'Audi A3 Sport',88500);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (2,'BWM X1 Sport',112000);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (3,'Citroen C4 Pallas',115000);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (4,'Fiat 500 Flex',42840);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (5,'Palio Weekend',42540);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (6,'Agile 2014',27990);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (7,'Captiva Flex',69000);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (8,'Civic 2014',74000);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (9,'Fit Sport',56000);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (10,'Veloster 2014',89000);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (11,'Elantra 2014',88500);
INSERT INTO carros.carros_veiculo (modelo_id, veiculo, preco) VALUES (12,'i30 Sport',99000);
